# Generated by Django 3.2.9 on 2021-11-18 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20211117_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='image',
            field=models.URLField(default='https://www.pngfind.com/pngs/m/77-776106_mario-bros-coin-icon-hd-png-download.png'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('user', 'coin')},
        ),
    ]
